Fix/exceptions admin search
kucc/kubook-backend pull request #108
Opened 2024-11-29 15:36 UTC by sounmu

## 배경 (AS-IS)

Loan에 해당하는 User와 Book이 없을 경우 제대로 된 응답 메시지를 주지 않는 문제
## 변경 사항 (TO-BE)

명시적으로 없는 경우 HTTPException을 올리도록 수정

## 체크리스트
- [x] 긴급 PR: callout 라벨 추가 및 카카오톡에 공유
- [x] 담당 영역 라벨 추가 완료
- [x] 테스트 코드 작성/수정 완료
- [x] 관련 문서 업데이트 완료
- [x] Breaking Change 있는 경우 관련 팀 공유 완료

2024-11-30 12:32 UTC, smreosms13 commented on src/domain/services/admin/loan_service.py
> +                )
이 에러가 났다는 건 대출 신청 API가 잘못되었다는 건데, 혹시 실행중에 에러가 났나요?
search, read api에서 모두 에러가 났는지?

2024-11-30 12:48 UTC, sounmu commented on src/domain/services/admin/loan_service.py
> +                )
연결된 book이나 user 테이블에 데이터가 없으면 에러가 나게 하는건데, 3133 같이 없는 book_id 쓰는 경우 일단 명시적으로 표시한 겁니다

2024-11-30 12:58 UTC, smreosms13 commented on src/domain/services/admin/loan_service.py
> +                )
이렇게 에러 핸들링하고 나서, 에러가 실제로 일어났는지 묻는 거에요.

2024-11-30 13:38 UTC, sounmu commented on src/domain/services/admin/loan_service.py
> +                )
book_id가 잘못됐을 경우, 오류가 발생하긴 합니다. 사실 무결성이면 없어도 되긴 해서 ...

2024-11-30 15:09 UTC, smreosms13 commented on src/domain/services/admin/loan_service.py
> +                )
그럼 일단 로직 유지하는 걸로 합시다. 지금 에러는 수정 전 post loan api 때문에 나는 것 같은데 혹시 모르니까..

2024-11-30 15:26 UTC, smreosms13 requested changes

2024-11-30 15:26 UTC, smreosms13 commented on src/domain/services/admin/loan_service.py
> -        .options(joinedload(Loan.user), joinedload(Loan.book))
검색에서 아래와 같은 에러가 나고 있습니다.


{
  "detail": "Unexpected error occurred during retrieve: (pymysql.err.OperationalError) (1054, \"Unknown column 'book.book_title' in 'where clause'\")\n[SQL: SELECT loan.id, loan.book_id, loan.user_id, loan.loan_date, loan.due_date, loan.extend_status, loan.return_status, loan.return_date, loan.overdue_days, loan.created_at, loan.updated_at, loan.is_deleted \nFROM loan \nWHERE loan.is_deleted = false AND MATCH(book.book_title) AGAINST(%(book_title)s IN BOOLEAN MODE) AND MATCH(user.user_name) AGAINST(%(user_name)s IN BOOLEAN MODE) AND MATCH(category_name) AGAINST(%(category_name)s IN BOOLEAN MODE) AND loan.return_status = false ORDER BY loan.updated_at DESC]\n[parameters: {'book_title': 'book*', 'user_name': 'test*', 'category_name': 'category*'}]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)"
}

2024-11-30 16:02 UTC, sounmu commented on src/domain/services/admin/loan_service.py
> -        .options(joinedload(Loan.user), joinedload(Loan.book))
수정 했습니당

2024-11-30 16:03 UTC, sounmu commented on src/domain/services/admin/loan_service.py
> +                )
그럴 수도 있고 어차피 admin 로직이라 데이터에 문제 있으면 얘로 알 수도 있으면 좋으니?

2024-12-02 01:18 UTC, smreosms13 approved these changes

2024-12-02 01:57 UTC, merged