Feat/admin settings
kucc/kubook-backend pull request #113
Opened 2024-12-04 10:31 UTC by ywnjeong

## 배경 (AS-IS)
fix: typo bookrequest

## 변경 사항 (TO-BE)
- feat: get admin settings 기능 추가 

## 체크리스트
- [ ] 긴급 PR: callout 라벨 추가 및 카카오톡에 공유
- [ ] 담당 영역 라벨 추가 완료
- [ ] 테스트 코드 작성/수정 완료
- [ ] 관련 문서 업데이트 완료
- [ ] Breaking Change 있는 경우 관련 팀 공유 완료

2024-12-04 13:31 UTC, ywnjeong commented
- setting schema 변경
- get route 수정
- post admin setting 기능 추가

2024-12-04 13:46 UTC, smreosms13 requested changes

2024-12-04 13:46 UTC, smreosms13 commented on src/routes/admin/request/setting_request.py
> +    request_max_price: int = Field(title="request_max_price", description="도서 구매 신청 최대 금액", ge=0)
examples 추가하기

2024-12-04 13:46 UTC, smreosms13 commented on src/main.py
> +from routes.admin.setting_route import router as setting_router
setting_router -> admin_setting_router

2024-12-04 13:46 UTC, smreosms13 commented on src/domain/schemas/setting_schemas.py
> +        return Self
@model_validator로 하지 않기, 
```python
def is_service_duration(self, current_datetime: datetime) -> bool:
  if not (self.start_date <= current_datetime <= self.end_date):
              return False
  return True

```

2024-12-04 13:46 UTC, smreosms13 commented on src/domain/services/admin/setting_service.py
> +    return response
except HTTPException
except Exception (db, 라이브러리 에러 고려)
추가하기

2024-12-05 09:01 UTC, smreosms13 commented on src/routes/admin/setting_route.py
> +    domain_req.set_datetime()
service 함수 내에서 하기.

2024-12-26 12:05 UTC, smreosms13 approved these changes

2024-12-29 08:03 UTC, merged