Refactor: update_book_request_request/book_request_response dto 추가
kucc/kubook-backend pull request #25
Opened 2024-08-15 12:34 UTC by imyouna

2024-08-28 13:33 UTC, smreosms13 requested changes

2024-08-28 13:33 UTC, smreosms13 commented on src/routes/user_book_request_route.py
> +import domain.services.book_request_service as book_request_service
파일 전체가 아닌 필요한 함수만 Import 해주세요
- req, res 대신 다른 이름으로 import 해주세요

2024-08-28 13:33 UTC, smreosms13 commented on src/domain/services/book_request_service.py
> +    requested_book = db.query(RequestedBook).filter(RequestedBook.id == request_id).first()
sqlAlchemy 2.0 버전 코드로 수정해주세요

2024-08-28 13:33 UTC, smreosms13 commented on src/domain/schemas/book_request_schemas.py
>      book_title: str = Field(..., title="book_title", description="책 제목", example="FastAPI Tutorial")
```python
book_title :str = Field(title="book_title", description="책 제목", example="FastAPI Tutorial"
``` 
Field 안에 `...` 지워주세요

2024-08-28 13:33 UTC, smreosms13 commented on src/domain/schemas/book_request_schemas.py
>      book_title: str = Field(..., title="book_title", description="책 제목", example="FastAPI Tutorial")
나머지 Field들도 수정 바랍니다!

2024-08-28 13:33 UTC, smreosms13 commented on src/domain/schemas/book_request_schemas.py
>      publication_year: int = Field(..., title="publication_year", description="출판년도", example=2022, ge=0)
`ge` 대신 `gt`를 사용해주세요

ge = greater or equal
gt = greater than

2024-08-28 13:33 UTC, smreosms13 commented on src/domain/schemas/book_request_schemas.py
>      publication_year: int = Field(..., title="publication_year", description="출판년도", example=2022, ge=0)
다른 곳에도 마찬가지로 수정 바랍니다

2024-08-28 13:33 UTC, smreosms13 commented on src/domain/schemas/book_request_schemas.py
>      id: int = Field(..., title="book_request_id", description="도서 구매 요청 정보 id", example=1, ge=0)
id는 request_id로 바꿔주세요

2024-08-28 13:33 UTC, smreosms13 commented on src/domain/schemas/book_request_schemas.py
>      id: int = Field(..., title="book_request_id", description="도서 구매 요청 정보 id", example=1, ge=0)
다른 스키마도 동일하게 바꿔주시기 바랍니다

2024-08-28 13:33 UTC, smreosms13 commented on src/domain/schemas/book_request_schemas.py
> +class BookRequestUpdateResponse(BaseModel):
Update 빼기

2024-08-28 13:33 UTC, smreosms13 commented on src/domain/schemas/book_request_schemas.py
안 쓰는 스키마 지우기

2024-08-28 13:33 UTC, smreosms13 commented on src/domain/services/book_request_service.py
> +    update_item(User, request_data.user_id, request_data, db)
지우는 거 확인

2024-08-28 13:33 UTC, smreosms13 commented on src/domain/services/book_request_service.py
> +    requested_book = db.query(RequestedBook).filter(RequestedBook.id == request_data.id).first()
sqlAlchemy 2 버전
get_item() 써도 좋습니다

2024-08-28 13:33 UTC, smreosms13 commented on src/routes/response/book_request_response.py
> +class BookRequestResponse(BaseModel):
request_id 추가해주세요

2024-08-28 13:33 UTC, smreosms13 commented on src/domain/schemas/book_request_schemas.py
> +class BookRequestUpdateResponse(BaseModel):
request_id

2024-08-28 13:33 UTC, smreosms13 commented on src/routes/user_book_request_route.py
> +        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Request not found.")
domain_res가 빈 object가 아님을 검증할 것
에러시 500, detail

2024-08-28 13:33 UTC, smreosms13 commented on src/routes/user_book_request_route.py
> +    return {"status_code": status_code, "data": domain_res}
`"status_code": status_code,` 삭제

2024-08-28 13:33 UTC, smreosms13 commented on src/domain/services/user_service.py
> +    stmt = select(model).where((model.is_valid == True)).order_by(model.updated_at)
model.is_valid == True => model.is_deleted == False

2024-08-28 13:33 UTC, smreosms13 commented on src/domain/services/user_service.py
> +    stmt = select(model).where((model.id == index) and (model.is_valid == True))
model.is_valid == True => model.is_deleted == False

2024-08-28 13:33 UTC, smreosms13 commented on src/domain/services/user_service.py
> +    stmt = (update(model).where(model.id == index).values(is_valid=False))
is_deleted = True

2024-08-28 13:33 UTC, smreosms13 commented on src/utils/user_service.py
> +    stmt = select(model).where((model.is_valid == True)).order_by(model.updated_at)
model.is_valid == True => model.is_deleted == False

2024-08-28 13:33 UTC, smreosms13 commented on src/utils/user_service.py
> +    stmt = select(model).where((model.id == index) and (model.is_valid == True))
model.is_valid == True => model.is_deleted == False

2024-08-28 13:33 UTC, smreosms13 commented on src/utils/user_service.py
> +    stmt = (update(model).where(model.id == index).values(is_valid=False))
is_deleted=False

2024-08-29 13:40 UTC, smreosms13 commented on src/routes/request/update_book_request_request.py
> +
불필요한 코드 및 공백 삭제해주세요

2024-09-02 16:35 UTC, smreosms13 requested changes

2024-09-02 16:35 UTC, smreosms13 commented on src/domain/schemas/book_request_schemas.py
> +    user_id: int = Field(title="user_id", description="도서 구매를 요청한 사용자 ID", example=1, ge=0)
ge => gt로 변경

2024-09-02 16:35 UTC, smreosms13 commented on src/domain/schemas/book_request_schemas.py
> +    user_id: int = Field(title="user_id", description="도서 구매를 요청한 사용자 ID", example=1, ge=0)
다른 것도 같이 바꿔주세요

2024-09-02 16:35 UTC, smreosms13 commented on src/domain/services/book_request_service.py
> +from domain.schemas.book_request_schemas import ReadBookRequestRequest as read_bookreq_req
schema는 굳이 as 안 붙여도 괜찮을 것 같습니다.

2024-09-02 16:35 UTC, smreosms13 commented on src/domain/schemas/book_request_schemas.py
> +class ReadBookRequestRequest(BaseModel):
클래스명에서 ReqeustGetMyBookRequest로 하는 건 어떠신지?

2024-09-02 16:35 UTC, smreosms13 commented on src/domain/services/book_request_service.py
> +async def update_bookreq(request_data: update_bookreq_req, db: Session):
함수명은 중간에 단어를 끊지 말고 명확하게 써주세요. 

update_book_request 가 좋겠습니다

2024-09-02 16:35 UTC, smreosms13 commented on src/routes/user_book_request_route.py
> +from domain.schemas.book_request_schemas import ReadBookRequestRequest as domain_read_req
여기도 스키마에 별칭 필요 없을 것 같아요

2024-09-02 16:35 UTC, smreosms13 commented on src/routes/user_book_request_route.py
> +from domain.services.book_request_service import update_bookreq, read_bookreq
service함수는 as로  service_{import 하는 함수명} 형식으로 alias를 넣어주세요

2024-09-02 16:35 UTC, smreosms13 commented on src/routes/user_book_request_route.py
> +    return route_bookreq_res(domain_res)
result 변수에 service 함수의 반환값을 할당하고, result를 return할 것

2024-09-02 16:35 UTC, smreosms13 commented on src/routes/user_book_request_route.py
> +async def read_user_book_requests(
함수 이름은 get_my_book_requests 로 바꾸는게 더 명확할 것 같아요

2024-09-02 16:45 UTC, smreosms13 requested changes
지금은 괜찮지만 나중에 리팩토링된 브랜치에 pr할 때는 admin 폴더 내의 코드는 포함되지 않도록 주의 바랍니다

2024-09-02 16:45 UTC, smreosms13 commented on src/domain/services/book_request_service.py
> +    updated_book = get_item(RequestedBook, request_data.request_id, db)
get_item으로 다시 받아오는 이유가 있을까요?

```python
    # update_item 함수 코드 일부
        db.commit()
        db.refresh(item)
        return item
``` 
구체적으로 update_item 함수에서 `refresh`(DB에 저장된 객체의 최신상태 정보 조회)를 하고 
최신 정보를 반환하기 때문에  get_item으로 새 정보를 다시 받아올 필요는 없습니다

```python
    result = update_item()
``` 
 get_item을 쓰지 않고 updated_book 변수에 update_item의 반환값을 할당하면 됩니다.

2024-09-05 06:12 UTC, imyouna commented on src/routes/user_book_request_route.py
> +async def read_user_book_requests(
혹시 update 함수명도 update_user_bookrequest에서 update_my_bookrequest로 바꿔야할까요?

2024-09-05 06:13 UTC, imyouna commented on src/domain/services/book_request_service.py
> +    updated_book = get_item(RequestedBook, request_data.request_id, db)
수정했습니다 감사합니다!

2024-09-10 05:35 UTC, closed without merging