Feat: 전체 대출 목록 조회, 대출 연장 기능 추가
kucc/kubook-backend pull request #26
Opened 2024-08-18 08:08 UTC by sounmu

- [ ]  schemas/loan_schemas.py LoanListItem, LoanListResponse, LoanExtendResponse 클래스 추가
- [ ]  services/loan_service.py get_all_user_loans.py, extend_loan 함수 추가 
- [ ]  routes/loan_route.py PUT "/{loan_id}/extend" 추가
- [ ]  routes/user_route.py GET "/{user_id}/loans" 추가

2024-08-21 13:19 UTC, smreosms13 commented on src/domain/schemas/loan_schemas.py
> +class LoanListItem(BaseModel):
LoanItem

2024-08-21 13:21 UTC, smreosms13 commented on src/domain/schemas/loan_schemas.py
> +    return_date: Optional[date]
Field 정보를 넣어주세요.
nullable(default value), title, description, example, 범위값(le, ge)

2024-08-21 13:21 UTC, smreosms13 commented on src/domain/schemas/loan_schemas.py
> +    data: List[LoanListItem] = Field(..., title="loan_list", description="대출 정보 리스트")
필드 값 지우기.

2024-08-21 13:25 UTC, smreosms13 commented on src/domain/services/loan_service.py
> +    loans = db.query(Loan).filter(Loan.user_id == user_id).all()
sqlalchemy 2.0 코드로 변경

2024-08-28 13:43 UTC, smreosms13 requested changes

2024-08-28 13:43 UTC, smreosms13 commented on src/domain/services/loan_service.py
> +        raise HTTPException(status_code=404, detail="No loans found")
빈 배열이 아닌지도 확인하기
status_code 는 status 라이브러리

2024-08-28 13:43 UTC, smreosms13 commented on src/domain/services/loan_service.py
> +    db.refresh(loan)
try-catch 문 활용하여 에러 핸들링

2024-08-28 13:43 UTC, smreosms13 commented on src/domain/schemas/loan_schemas.py
> +    id: int = Field(..., title="loan_id", description="대출 정보 id", example=1, ge=0)
loan_id로 바꿔주시기 바랍니다!

Field 의 `...` 지워주세요!
```python
book_title :str = Field(title="book_title", description="책 제목", example="FastAPI Tutorial"
```

2024-08-28 13:43 UTC, smreosms13 commented on src/domain/schemas/loan_schemas.py
> +    id: int = Field(..., title="loan_id", description="대출 정보 id", example=1, ge=0)
다른 스키마도 수정바랍니다

2024-08-28 13:43 UTC, smreosms13 commented on src/routes/loan_route.py
> +import domain.services.loan_service as loan_service
필요하신 함수, 스키마만 import 해주세요

2024-08-28 13:43 UTC, smreosms13 commented on src/domain/services/loan_service.py
> +    stmt = select(Loan).filter(Loan.user_id == request.user_id, Loan.id == request.loan_id)
stmt = select(Loan).filter(Loan.id == request.loan_id, Loan.is_deleted == False)

2024-08-28 13:43 UTC, smreosms13 commented on src/domain/services/loan_service.py
> +                                detail="Loan not found")
get_item() 함수로 대체하셔도 됩니다.

2024-08-28 13:43 UTC, smreosms13 commented on src/domain/services/loan_service.py
> +                                detail="Loan not found")
loan.user_id가 request.user_id와 같은지 검증하는 로직을 추가해주세요

2024-08-28 13:43 UTC, smreosms13 commented on src/routes/user_route.py
> +import domain.services.loan_service as user_loan_service
필요한 스키마와 함수만 import 해 주세요

2024-08-28 13:43 UTC, smreosms13 commented on src/domain/services/loan_service.py
> +    stmt = select(Loan).filter(Loan.user_id == user_id)
stmt = select(Loan).filter(Loan.user_id == user_id, Loan.is_deleted == False)

삭제가 is_deleted의 값만 변경시키고 실제로 db에서 삭제하지는 않기 때문에, 삭제되지 않은 유효한 데이터를 가져오기 위해서는  is_deleted의 값을 검증해야 합니다

2024-08-28 13:43 UTC, smreosms13 commented on src/routes/user_route.py
> +    summary="전체 대출 목록 조회",
"회원의 전체 대출 목록 조회"로 summary를 변경해주세요

2024-08-28 14:46 UTC, smreosms13 commented on src/domain/services/loan_service.py
> +                                detail="Loan not found")
기존 admin_service에 변경사항이 있습니다. 아래 노션 페이지 참고하셔서 변경해주세요
https://www.notion.so/_service-py-78b80c9419f3443ba931efb76b18ad07?pvs=4

2024-08-28 14:57 UTC, smreosms13 requested changes

2024-08-28 14:57 UTC, smreosms13 commented on src/domain/schemas/loan_schemas.py
> +
이전 회의에서 논의했던 대로 `count : data 배열의 요소 개수(int)`를 추가해주세요

2024-08-28 14:57 UTC, smreosms13 commented on src/routes/user_route.py
> +    return await user_loan_service.get_all_user_loans(current_user.id, db)
response_model에 정의한 것과 다르게 return 되지 않는지 확인해주세요
data key값에 대해 loan 배열이 있어야 하고, count 값을 추가해주세요

2024-08-28 14:57 UTC, smreosms13 commented on src/routes/loan_route.py
> +    return await loan_service.extend_loan(request, db)
가독성과 디버깅을 위해
await loan_servixe.extend_loan(reqeust,db)의 값을 변수에 담고, 그 변수를 return 해주시기 바랍니다

```python
result = await loan_service.extend_loan(request, db)
return result

``` 

다른 코드도 같이 수정바랍니다

2024-08-29 14:51 UTC, smreosms13 requested changes

2024-08-29 14:51 UTC, smreosms13 commented on src/domain/schemas/loan_schemas.py
> +
폴더가 domain인 걸 몰랐네요. 이 클래스는 routes의 response에 있어야 합니다.

2024-08-29 16:35 UTC, sounmu commented on src/domain/schemas/loan_schemas.py
> +
LoanExtendRequest도 routes의 request로 옮겼습니다

2024-08-29 17:39 UTC, sounmu commented
1. route에서 service의 함수와 이름이 중복되는 문제를 해결하기 위해 import Func as service_Func 형태로 수정
2. LoanExtendRequest 스키마도 routes/request/loan_request.py로 위치 변경
3. 그 외 코멘트 주신대로 수정 했습니다.

2024-09-02 16:10 UTC, smreosms13 requested changes

2024-09-02 16:10 UTC, smreosms13 commented on src/domain/services/loan_service.py
> +        loan.overdue_days = 0
db에서 받아온 loan과 달라지지 않으므로 필요하지 않을 것 같습니다

2024-09-02 16:10 UTC, smreosms13 commented on src/domain/schemas/loan_schemas.py
> +    created_at: _datetime = Field(title="create_at", description="생성일시", example=_datetime.now())
LoanBase > LoanInfo > Loan 순으로 상속되고 있는데, 저희 스키마 내 상속은 가급적 지양하기로 했습니다.
아래의 LoanItem이 있기 때문에 지워주셔도 좋습니다.

2024-09-02 16:12 UTC, smreosms13 commented on src/domain/schemas/loan_schemas.py
> +
> LoanExtendRequest도 routes의 request로 옮겼습니다

LoanExtendRequest는 domain의 request이기 때문에 domain/schemas/loan_schemas.py에 있는 것이 맞습니다.
다시 재위치시켜 주세요

2024-09-02 16:14 UTC, smreosms13 commented on src/domain/services/loan_service.py
> +        loan.overdue_days = 0
models.py의 Loan을 보시면 이미 overdu_days에 0을 기본값으로 주고 있습니다.

2024-09-12 04:04 UTC, closed without merging