Feat: 내 도서구매 요청목록 조회, 수정 api 구현
kucc/kubook-backend pull request #28
Opened 2024-09-05 07:36 UTC by imyouna

- [ ] 사용자 도서 구매 요청 목록 조회
- [ ] 사용자 도서 구매 요청 수정

2024-09-05 07:40 UTC, imyouna commented on src/domain/services/bookrequest_service.py
> +    if request_data.user_id:
이거 오류 뜰 때 추가해둔건데, if문 지워서 최종 올려두겠습니다

2024-09-05 07:40 UTC, imyouna commented on src/routes/user_bookrequest_route.py
> +    ) for item in domain_res]
domian_res에는 domain response DTO list를 받아서, converted_res로 route response DTO로 변환하는 작업 넣었습니다.

2024-09-05 07:40 UTC, imyouna commented on src/routes/user_bookrequest_route.py
> +        request_date=domain_res.request_date,
DB에는 requested_at이 DateTime으로 있어서 혼란스러워서, 
class에는 Date만 쓰는 것 같아 request_date로 전부 수정했습니다.

2024-09-12 14:35 UTC, smreosms13 requested changes
공통 수정 사항
파일명, 함수명에서 bookrequest -> book_request로 바꿀 것

스키마 이름 규칙을 하나로 통일할 것

2024-09-12 14:35 UTC, smreosms13 commented on src/domain/schemas/bookrequest_schemas.py
> +class DeleteBookRequestRequest(BaseModel):
클래스 이름 규칙을 정해둘 것. 위의 클래스 이름과 지금 클래스 이름 규칙이 다릅니다
위는 Request+ Method + Domain 인 것 같은데 이게 좋아 보여요

다른 클래스 이름도 하나의 규칙으로 이름을 정해주세요

2024-09-12 14:35 UTC, smreosms13 commented on src/domain/services/bookrequest_service.py
> +
update_item 안에 get_item 호출하여 검사하는 로직이 있는데 따로 실행하는 이유가 있나요?

2024-09-12 14:35 UTC, smreosms13 commented on src/domain/services/bookrequest_service.py
> +        )
python list comprehension 검색해보세요, 
당장 userbookrequest_route.py line 29에 쓰인 코드처럼 바꾸면 됩니다

2024-09-12 14:35 UTC, smreosms13 commented on src/domain/services/bookrequest_service.py
> +
여기도 update_item 바깥에서 get_item 호출하는 이유가 있나요

2024-09-12 14:35 UTC, smreosms13 commented on src/routes/user_bookrequest_route.py
book_request_route.py와 통합해주세요

2024-09-12 14:35 UTC, smreosms13 commented on src/routes/user_bookrequest_route.py
> +async def get_my_bookrequests(
합성어에는 웬만해서 _ 넣어주세요

2024-09-12 14:35 UTC, smreosms13 commented on src/routes/user_bookrequest_route.py
> +    "/{user_id}/book-requests",
/book-request로 변경하고 book_request_route.py에 통합해주세요

2024-09-12 14:35 UTC, smreosms13 commented on src/routes/user_bookrequest_route.py
> +    user_id: int,
user_id 삭제하고 current_user에서 id 가져오기
my_requests: bool = False # 쿼리 매개변수 추가 (True - 자신의 구매 요청만 조회, False면 전체 조회)

2024-09-12 14:35 UTC, smreosms13 commented on src/routes/user_bookrequest_route.py
> +    "/{user_id}/book-requests/{request_id}",
마찬가지로 /{user_id} 빼고 user_id는 current_user에서 가져올 것

2024-09-12 14:35 UTC, smreosms13 commented on src/routes/user_bookrequest_route.py
> +    user_id: int,
my_request의 값에 따라 service 함수에서 로직이 달라져야 할 겁니다.

2024-09-12 14:35 UTC, smreosms13 commented on src/domain/services/bookrequest_service.py
> +    )
my_request가 true일 때 이렇게 조회하고
아니라면 get_list 호출하면 됩니다

2024-09-25 15:03 UTC, merged