feat: 도서 대출 신청, 리뷰 작성 기능 추가
kucc/kubook-backend pull request #33
Opened 2024-09-12 04:02 UTC by sounmu

- [ ] models.py Loan status str에서 bool로 변경.
- [ ] sql에 위 사항을 반영
- [ ] create_loan, create_review 라우트, 서비스 생성

2024-09-12 05:43 UTC, imyouna commented on src/routes/user_route.py
> +async def get_all_user_loans(
user_id: int 추가해주세요!

2024-09-12 05:43 UTC, imyouna commented on src/routes/response/loan_response.py
> +    data: List[LoanListResponse]
18번 줄을 data: List[LoanResponse]로 해야 맞는 것 같습니다!
(+ 저는 list말고 개별 response는 LoanResponse처럼 했는데, LoanCreateResponse로 할지 아니면 LoanResponse로 할지 정해야 할 것 같습니다)

2024-09-12 05:43 UTC, imyouna commented on src/routes/response/book_review_response.py
> +    data: List[BookReviewItem]
여기도 List[BookReviewCreateResponse]가 맞을 것 같아요

2024-09-12 05:43 UTC, imyouna commented on src/routes/loan_route.py
> +    result = await service_extend_loan(request.loan_id, request.user_id, db)
이거 request로 이미 dto 만들었는데 굳이 하나씩 쪼개서 파라미터로 건네주지 말고, service_extend_load(request, db)로 하는게 나을 것 같습니다

2024-09-12 05:43 UTC, imyouna commented on src/domain/services/loan_service.py
> +async def extend_loan(loan_id, user_id, db: Session):
파라미터 도메인 Request dto로 통으로 넘겨주세요!

2024-09-12 05:43 UTC, imyouna commented on src/domain/services/loan_service.py
> +                                detail="This loan has already been returned.")
이거 스웨거에서 테스트해봤는데 404 error 나는데 확인 부탁합니다!

2024-09-12 05:43 UTC, imyouna commented on src/routes/loan_route.py
> +    result = await service_create_loan(request.user_id, request.book_id, db)
여기도 request dto 통으로 넘겨주세요!

2024-09-12 05:43 UTC, imyouna commented on src/domain/services/loan_service.py
> +async def create_loan(user_id, book_id, db: Session):
파라미터 dto 통으로 받아주세요!

2024-09-12 05:43 UTC, imyouna commented on src/domain/services/loan_service.py
> +    )
이거 utils.curd_utils의 create_item() 사용하면 더 편할 것 같아요

2024-09-12 06:11 UTC, imyouna commented
Request, Response dto 사용하는 예시 수빈님이랑 제 pr 참고해주시면 도움 될 것 같습니다!

2024-09-12 06:12 UTC, sounmu commented on src/routes/response/loan_response.py
> +    data: List[LoanListResponse]
일단 LoanResponse로 해두겠습니다!

2024-09-12 06:37 UTC, sounmu commented on src/domain/services/loan_service.py
> +    )
일단 더 안 편한거 같아서 안 쓰겠습니다..ㅠ

2024-09-12 06:40 UTC, sounmu commented on src/domain/services/loan_service.py
> +                                detail="This loan has already been returned.")
이거는 고쳤습니다!

2024-09-12 06:49 UTC, sounmu commented on src/routes/user_route.py
> +async def get_all_user_loans(
아이디는 current_user.id로 도메인에 넘기고 있어서 필요 없을거 같습니다.

2024-09-12 07:10 UTC, imyouna commented
404 오류 해결된거 확인했습니다!
DELETE reviews/{review_id}: 이미 삭제된 것도 또 삭제 가능한 오류
GET reviews/{user_id}/load api: "loan"아니고 "review"인 것 같아요(endpoint 오타) + 삭제된 리뷰도 조회가 가능한 오류

이것도 수정부탁합니당

2024-09-12 14:55 UTC, sounmu commented
domain/services/book_review_service.py 와 loan_service.py에 create_review와 create_loan함수에서 각각 리뷰 작성, 대출 신청을 하는 과정에서 외래 키를 검증하는 단계를 추가했습니다

2024-09-13 02:24 UTC, smreosms13 requested changes

2024-09-13 02:24 UTC, smreosms13 commented on src/domain/services/book_review_service.py
> +        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
if문에 db.execute(stmt).scalar_one_or_none()을 넣기보다 그 전에 변수에 할당해 검사해주세요

2024-09-13 02:24 UTC, smreosms13 commented on src/domain/services/book_review_service.py
> +                            detail=f"Integrity Error occurred during create the new review item. {str(e)}")
현재 IntegrityError가 잡히지 않습니다. except문을 제거하거나 다른 방식으로 구현해주세요

2024-09-13 02:24 UTC, smreosms13 commented on src/domain/services/loan_service.py
> +                            detail=f"Invalid book ID")
위의 댓글에서 말한 수정사항과 같습니다

2024-09-20 06:59 UTC, merged