Feat/user bookrequest
kucc/kubook-backend pull request #52
Opened 2024-10-07 01:42 UTC by imyouna

- 유저의 도서구매 내역 조회, 수정, 삭제 api
- 이미 삭제한 도서는 중복 상제 방지, 조회 안 됨
- 도서구매 내역 수정은 요청한 사용자만 가능

- DELETE book-requests/{request_id} 라우터를 users/{user_id}/book-request 라우터 파일과 병합
(crud_utils의 create_item, update_item을 다른 분이 작업하는 곳에서 사용 중이라 실행을 위해 일단 주석 해제했습니다)

2024-10-07 02:36 UTC, smreosms13 reviewed
코멘트 참고하여 수정바랍니다

2024-10-07 02:36 UTC, smreosms13 commented on src/domain/services/bookrequest_service.py
> +        reason=item.reason,
들여쓰기 넣어주세요

2024-10-07 02:36 UTC, smreosms13 commented on src/domain/services/bookrequest_service.py
> +                 RequestedBook.user_id==request_data.user_id,
pk인 request_id로 검색하면 어차피 한 데이터만 나오기 때문에 user_id를 검색할 필요가 없습니다.
기존대로 get_item 함수쓰면 됩니다.

만약 현재 api를 호출하는 user_id(request 안의 user_id)와 requested_book data 안의 user_id를 비교하려면 
get_item으로 받아온 return 값의 user_id와 비교하는 것이 맞습니다. (아니라면 403 forbidden error)

```python
requested_book = get_item(request_data.request_id)
if( requested_book.request.user_id != request_data.user_id) raise 403 error
 ```

2024-10-07 02:36 UTC, smreosms13 commented on src/domain/services/bookrequest_service.py
> +        raise e
HTTPException 은 Exception 중 하나라서 굳이 없어도 될 것 같아요

2024-10-07 02:36 UTC, smreosms13 commented on src/domain/services/bookrequest_service.py
> +                status_code=status.HTTP_404_NOT_FOUND, detail="Requested book not found")
위에서 get_item을 사용한다면 이 코드도 필요없습니다.

2024-10-07 02:36 UTC, smreosms13 commented on src/domain/services/bookrequest_service.py
>      return
API 를 호출하는 user의 id가 requested_book의 user_id와 일치하는지 확인(아니면 raise 403 error)해주세요. 

참고
```python
    review = get_item(BookReview, review_id, db)

    if review.user_id != user_id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You do not have permission to access this review."
            )
            status_code=status.HTTP_403_FORBIDDEN, detail="You do not have permission to access this review."
        )

```

2024-10-07 03:24 UTC, sounmu approved these changes
수빈님이 남긴 수정사항만 고치면 될거 같습니다

2024-10-08 04:49 UTC, imyouna commented
도서 구매 요청 삭제하는 도메인 스키마 수정했습니다 (user_id, is_deleted 추가)
구매 요청 삭제 시 delete_item 대신에 도메인 스키마에 있는 값들로 update 하는 방식으로 수정했습니다

2024-10-08 09:51 UTC, smreosms13 requested changes
코멘트 확인하여 수정해주세요

2024-10-08 09:51 UTC, smreosms13 commented on src/domain/schemas/bookrequest_schemas.py
> +    is_deleted: bool = Field("is_delted", description="삭제 여부")
이거 service 함수에서 쓰고 있나요? 굳이 없어도 될 것 같습니다.
processing_status도 사실 필요 없는게, 사용자측에서 도서 신청 취소(status = 2)하는 거니까 굳이 input으로 받지 않아도 됩니다

2024-10-08 09:51 UTC, smreosms13 commented on src/domain/services/bookrequest_service.py
> +                    )
여기 로직이 schema의 값으로 기존 데이터를 대체하는 건데,
이 api에서 바꿀 건 정해져 있으니(processing_status = 2, is_deleted=True)
굳이 for문으로 schema 하나씩 조회하지 않고, 바로 requestd_data 수정하는게 좋겠습니다.

2024-10-08 09:51 UTC, smreosms13 commented on src/routes/user_bookrequest_route.py
> +    domain_req = DomainReqDelBookRequest(user_id=current_user.id, request_id=request_id, processing_status=2, is_deleted=1)
processing_status = 2, is_deleted = 1 값은 필요없을 것 같아요

2024-10-09 05:24 UTC, smreosms13 approved these changes

2024-10-09 05:30 UTC, merged