feat: admin-loan-return|unreturn 대출 반납 상태 토글 기능 구현
kucc/kubook-backend pull request #65
Opened 2024-10-30 16:06 UTC by sounmu

- 관리자 페이지에서 대출 상태를 True 또는 False로 변경할 수 있는 기능을 추가했습니다

2024-11-05 11:27 UTC, smreosms13 reviewed
반납 로직 변경 가능성이 있어 이 기능은 잠시 보류

2024-11-05 11:27 UTC, smreosms13 commented on src/routes/admin/loan_route.py
> +    return response
이 기능 잠시 보류

2024-11-05 11:27 UTC, smreosms13 commented on src/domain/services/admin/loan_service.py
> +
이 기능 잠시 보류

2024-11-06 12:39 UTC, sounmu commented
- toggle true면 false로, false면 true로

2024-11-28 11:48 UTC, smreosms13 requested changes
loan_schemas에 안 쓰는 스키마는 제거, 
DomainResGetLoanItem과 DomainResGetLoan 중 하나로 통일하기

2024-11-28 11:48 UTC, smreosms13 commented on src/domain/services/admin/loan_service.py
> +    loan_id,
type int를 밝혀주세요

2024-11-28 11:48 UTC, smreosms13 commented on src/domain/services/admin/loan_service.py
> +from domain.schemas.loan_schemas import DomianResGetLoanItem
스키마 이름 오타 고치기 
DomainResGetLoanItem

2024-11-28 11:48 UTC, smreosms13 commented on src/domain/services/admin/loan_service.py
> +        result = DomianResGetLoanItem(
스키마 이름 오타 고치기
DomainResGetLoanItem

2024-11-28 11:48 UTC, smreosms13 commented on src/routes/admin/loan_route.py
> +from domain.schemas.loan_schemas import DomianResGetLoanItem
스키마 이름 오타 고치기
DomainResGetLoanItem

2024-11-28 11:48 UTC, smreosms13 commented on src/domain/services/admin/loan_service.py
> +async def service_admin_toggle_loan_return(
굳이 'toggle'이라고 밝히지 않아도 괜찮습니다.

2024-11-28 13:21 UTC, sounmu commented
@ 이걸로 사람 태그가 되는 줄 모르고 했습니다 .... ㅠ

2024-11-28 13:40 UTC, smreosms13 approved these changes

2024-11-29 04:51 UTC, merged