Feat/admin bookrequest
kucc/kubook-backend pull request #93
Opened 2024-11-27 14:42 UTC by imyouna

## 변경 사항 (TO-BE)
- admin 도서 구매 요청 목록 조회 추가 (pagination 추가)
- admin 도서 구매 요청 processing status 변경(PUT) 추가
- admin 도서 구매 요청 삭제 추가

## 체크리스트
- [x] 긴급 PR: callout 라벨 추가 및 카카오톡에 공유
- [x] 담당 영역 라벨 추가 완료
- [x] 테스트 코드 작성/수정 완료
- [x] 관련 문서 업데이트 완료
- [x] Breaking Change 있는 경우 관련 팀 공유 완료

2024-11-28 11:12 UTC, smreosms13 requested changes

2024-11-28 11:12 UTC, smreosms13 commented on src/routes/admin/response/bookrequest_response.py
> +    count: int
total 추가해주세요

2024-11-28 11:12 UTC, smreosms13 commented on src/routes/admin/request/bookrequest_request.py
> +    reject_reason: str | None = Field(None, title="reject_reason", description="거절 사유", example="Not available")
@model_validator를 사용하여 
processing_status가 3일 때, if not reject_reason 이면 Exception raise 해주세요

2024-11-28 11:12 UTC, smreosms13 commented on src/domain/services/admin/bookrequest_service.py
> +    stmt = select(RequestedBook).where(and_(RequestedBook.id==request_id, RequestedBook.is_deleted==False))
and_ 안쓰고 ,로 구분하면 여러 조건절도 실행 가능합니다.

2024-11-28 11:12 UTC, smreosms13 commented on src/domain/services/admin/bookrequest_service.py
> +        detail="Not found"
detail : BookRequest Not Found 로 수정해주세요

2024-11-28 11:12 UTC, smreosms13 commented on src/domain/services/admin/bookrequest_service.py
> +      )
아래 수정사항 참고

2024-11-28 11:12 UTC, smreosms13 commented on src/domain/schemas/bookrequest_schemas.py
> +    count: int
count를 total로 변경해주세요

2024-11-28 11:12 UTC, smreosms13 commented on src/domain/services/admin/bookrequest_service.py
> +    if offset>=total_count:
if ceil(total/limit) <page:

2024-11-28 11:12 UTC, smreosms13 commented on src/domain/services/admin/bookrequest_service.py
> +      )
BookRequest Not Found로 수정

2024-11-28 11:12 UTC, smreosms13 commented on src/domain/services/admin/bookrequest_service.py
> +    )
count -> total로 변경

2024-11-28 11:12 UTC, smreosms13 commented on src/domain/services/admin/bookrequest_service.py
> +      )
BookRequestStatus.REJECTED.value 대신 BookRequestStatusREJECTED()로 value 호출 가능합니다.

print(BookRequestStatusREJECTED()) # 3

2024-11-28 11:12 UTC, smreosms13 commented on src/domain/services/admin/bookrequest_service.py
> +      )
is_valid_enum_value 내의 함수로 status가 Enum 내의 값인지 검사 가능합니다. status.py 참고

```python
if is_valid_enum_value(BookRequestStatus, request.processing_status): 
```

2024-11-28 11:12 UTC, smreosms13 commented on src/routes/admin/bookreqeust_route.py
> +    )
total = domain_result.total,
count = len(domain_result)

2024-11-28 11:12 UTC, smreosms13 commented on src/routes/admin/response/bookrequest_response.py
> +    publication_year: int = Field(0, title="publication_year", description="출판년도", example=2022, gt=0)
gt =0 인 조건에서 default를 0으로 두면 에러가 납니다. default 값을 없애주세요

2024-11-28 11:14 UTC, smreosms13 commented
```python
    except HTTPException as e:
        raise e from e
``` 

exception이 400인데 500 에러로 나는 상황이 없는지 검수해주세요

2024-11-29 07:43 UTC, imyouna commented on src/domain/services/admin/bookrequest_service.py
> +      )
저는 이게 안돼요.. 😢

2024-11-29 08:36 UTC, smreosms13 commented on src/routes/admin/request/bookrequest_request.py
> +        if self.processing_status == 3 and not self.reject_reason:
== 3 대신 Enum을 사용해보세요

2024-11-29 08:36 UTC, smreosms13 commented on src/domain/services/admin/bookrequest_service.py
> +from repositories.models import RequestedBook
ruff 안 걸리는지 확인해주세요

2024-11-29 08:36 UTC, smreosms13 commented on src/domain/services/admin/bookrequest_service.py
> +      )
if ceil(total/limit) <page: 로 조건문 변경

2024-11-29 08:36 UTC, smreosms13 commented on src/domain/services/admin/bookrequest_service.py
> +    bookrequest = db.execute(stmt).scalars().all()
아래 limit, page 검사 이후 db에서 data 가져오는 게 좋겠습니다

2024-11-29 08:36 UTC, smreosms13 commented on src/domain/services/admin/bookrequest_service.py
> +      )
service 함수가 아닌 RouteReqAdminPutBookRequest에서 @field_validator를 이용하여 검사하기

[https://docs.pydantic.dev/latest/concepts/validators/#field-validators](url)

2024-11-29 11:06 UTC, smreosms13 approved these changes

2024-11-29 11:15 UTC, merged

2024-11-29 12:39 UTC, smreosms13 commented on src/routes/admin/request/bookrequest_request.py
> +
from typing_extension import Self